version: "3"
services:
  app-staging:
    container_name: app-staging
    tty: true
    restart: always
    build: 
      context: .
      dockerfile: ./Dockerfile.staging      
    ports:
      - 3000:80
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
