version: "3"
services:
  app-dev:
    container_name: app-dev
    tty: true
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  test:
    container_name: test
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm test
  test-watch:
    container_name: test-watch
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run test:watch
  test-coverage:
    container_name: test-coverage
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run test:coverage
  setup:
    container_name: setup
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./src/index.html:/app/src/index.html
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: node setup/setup.js

volumes:
  node_modules:
