# Use Node as the build image
FROM node:13.12.0-alpine as builder

# Set working directory
WORKDIR /app

# Install app dependencies
COPY package.json package.json
COPY package-lock.json package-lock.json

# Install node dependencies
RUN npm install --silent

# Copy app files to the container
COPY . .

# Use Node Alpine as the base image
FROM node:13.12.0-alpine

# Copy the build to the nginx root directory
COPY --from=builder /app /app

# Set the working directory
WORKDIR /app

# Expose port 3000
EXPOSE 3000

# Start the application
CMD ["npm", "run", "start"]
